apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  selector:
    matchLabels:
      app: flask-myapp
  template:
    metadata:
      labels:
        app: flask-myapp
    spec:
      containers:
      - name: flask-myapp
        image: lavi1205/project3_thinh:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
